#!/usr/bin/env python3
"""
Fetches the IACR ePrint Archive's recent-papers RSS feed and matches papers
against CRIYPT's own researcher directory, writing matches to
_data/recent_papers.yml for the homepage's "Recent Papers" section.

Matching is deliberately strict (exact, case/accent-insensitive full-name
match) rather than fuzzy — with a small, known list of researchers, a
missed match is a far better failure mode than misattributing a paper to
the wrong person on a public page.
"""
import re
import sys
import unicodedata
import urllib.request
import xml.etree.ElementTree as ET
from email.utils import parsedate_to_datetime
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
NAMES_FILE = REPO_ROOT / "_data" / "names-people.yml"
OUTPUT_FILE = REPO_ROOT / "_data" / "recent_papers.yml"
FEED_URL = "https://eprint.iacr.org/rss/rss.xml?order=recent"
USER_AGENT = (
    "CRIYPT-site-bot/1.0 "
    "(+https://github.com/cryptography-research-india/cryptography-research-india.github.io)"
)
MAX_PAPERS = 30


def slugify(name):
    slug = name.strip().lower()
    slug = re.sub(r"[^a-z0-9]+", "-", slug)
    return slug.strip("-")


def normalize(name):
    # Fold accents (e.g. "e" with acute -> "e") and collapse whitespace so
    # minor encoding differences between the site's data and ePrint's don't
    # cause a false negative.
    nfkd = unicodedata.normalize("NFKD", name)
    ascii_name = nfkd.encode("ascii", "ignore").decode("ascii")
    return re.sub(r"\s+", " ", ascii_name).strip().lower()


def load_researchers():
    with open(NAMES_FILE, encoding="utf-8") as f:
        people = yaml.safe_load(f) or []
    researchers = []
    for person in people:
        name = person.get("name")
        if not name:
            continue
        researchers.append({
            "name": name,
            "slug": slugify(name),
            "normalized": normalize(name),
        })
    return researchers


def fetch_feed():
    req = urllib.request.Request(FEED_URL, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(req, timeout=30) as resp:
        return resp.read()


def parse_pubdate(raw):
    try:
        return parsedate_to_datetime(raw).date().isoformat()
    except Exception:
        return None


def parse_items(xml_bytes):
    root = ET.fromstring(xml_bytes)
    items = []
    for item in root.iter("item"):
        title = (item.findtext("title") or "").strip()
        link = (item.findtext("link") or "").strip()
        pub_raw = (item.findtext("pubDate") or "").strip()
        if not title or not link:
            continue
        creators = []
        for child in item:
            # Match by local tag name so this doesn't depend on getting the
            # exact Dublin Core namespace URI right.
            local_tag = child.tag.rsplit("}", 1)[-1]
            if local_tag == "creator" and child.text:
                creators.append(child.text.strip())
        items.append({
            "title": title,
            "url": link,
            "date": parse_pubdate(pub_raw),
            "raw_authors": creators,
        })
    return items


def match_papers(items, researchers):
    by_normalized = {r["normalized"]: r for r in researchers}
    matched = []
    for item in items:
        authors = []
        matched_names = []
        for raw_author in item["raw_authors"]:
            r = by_normalized.get(normalize(raw_author))
            if r:
                authors.append({"name": raw_author, "slug": r["slug"]})
                if r["name"] not in matched_names:
                    matched_names.append(r["name"])
            else:
                authors.append({"name": raw_author, "slug": None})
        if matched_names:
            matched.append({
                "title": item["title"],
                "url": item["url"],
                "date": item["date"],
                "authors": authors,
                "matched_names": matched_names,
            })
    return matched


def write_output(matched):
    matched.sort(key=lambda p: p["date"] or "", reverse=True)
    matched = matched[:MAX_PAPERS]
    header = (
        "# Recent papers by CRIYPT-listed researchers.\n"
        "# Auto-generated by fetch-recent-papers.yml from the IACR ePrint\n"
        "# Archive — do not edit by hand, this file is regenerated wholesale\n"
        "# on every scheduled run.\n"
    )
    body = yaml.safe_dump(matched, allow_unicode=True, sort_keys=False, default_flow_style=False)
    OUTPUT_FILE.write_text(header + body, encoding="utf-8")


def main():
    researchers = load_researchers()
    xml_bytes = fetch_feed()
    items = parse_items(xml_bytes)
    matched = match_papers(items, researchers)
    write_output(matched)

    print(f"Checked {len(items)} recent papers against {len(researchers)} researchers.")
    print(f"Matched {len(matched)} paper(s):")
    for p in matched:
        print(f"  - {p['title']!r} -- {', '.join(p['matched_names'])} ({p['url']})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
