title: Cryptography Researchers of India
description: Connecting cryptography researchers across India
url: "https://cryptography-research-india.github.io"
baseurl: ""
author:
  name: CRI Community
  email: cryptography.research.india@gmail.com

github_username: cryptography-research-india

# Build
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

# Pagination
paginate: 6
paginate_path: /posts/page:num/

# Include
include:
  - _pages

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

# Collections
collections:
  resources:
    output: true

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: "_pages"
    values:
      layout: page
